model:
  posterior_kwargs:
    activation: gelu
    batch_norm: false
    context_with_glu: false
    dropout: 0.0
    hidden_dims:
    - 32
    - 64
    - 128
    - 256
    - 512
    - 1024
    - 1024
    - 1024
    - 512
    - 128
    - 64
    - 32
    sigma_min: 0.0001
    theta_with_glu: false
    time_prior_exponent: 4
    type: DenseResidualNet
  type: flow_matching
task:
  name: two_moons
  num_train_samples: 100000
training:
  batch_size: 64
  early_stopping: true
  epochs: 100
  num_workers: 0
  optimizer:
    lr: 0.0002
    type: adam
  scheduler:
    factor: 0.2
    patience: 1
    type: reduce_on_plateau
  train_fraction: 0.95
